version: 2.1

orbs:
  android: circleci/android@1.0.0

jobs:
  test-java:
    docker:
      - image: circleci/openjdk:17.0-jdk-buster
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Copy local.properties
          command: echo "sdk.dir=/usr/local/android-sdk-linux" > $HOME/project/local.properties

  build:
    docker:
      - image: circleci/openjdk:17.0-jdk-buster
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Copy local.properties
          command: echo "sdk.dir=/usr/local/android-sdk-linux" > $HOME/project/local.properties
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
